apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "dra-example-driver.fullname" . }}-webhook-config
  labels:
    {{- include "dra-example-driver.labels" . | nindent 4 }}
webhooks:
- name: "dra.example.com"
  rules:
  - apiGroups:   ["resource"]
    apiVersions: ["v1beta1"]
    operations:  ["CREATE", "UPDATE"]
    resources:   ["resourceclaims"]
    scope:       "Namespaced"
  clientConfig:
    service:
      namespace: "example-namespace"
      name: "example-service"
    # caBundle: <CA_BUNDLE>
  admissionReviewVersions: ["v1"]
  sideEffects: None
